"""add teaser

Revision ID: 29c544cde665
Revises: 90765737565b
Create Date: 2023-05-29 08:44:18.230324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '29c544cde665'
down_revision = '90765737565b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('teaser', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'teaser')
    # ### end Alembic commands ###
