"""added captcha schema

Revision ID: 9f3acd727a8a
Revises: 29c544cde665
Create Date: 2023-05-30 10:42:23.618648

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f3acd727a8a'
down_revision = '29c544cde665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('captcha_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captcha_id'), 'captcha', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captcha_id'), table_name='captcha')
    op.drop_table('captcha')
    # ### end Alembic commands ###
